language: python
python: 2.7
sudo: false
cache:
  pip: true
  directories:
    - $HOME/downloads
    - /home/travis/build/tisto/django-solr/downloads
env:
  - SOLR_VERSION=6.3.0
before_install:
  - mkdir -p $HOME/downloads
install:
  - make SOLR_VERSION=6.3.0
script:
#  - py.test
